Rails.application.routes.draw do
  get 'shoutouts/s1'
  get 'shoutouts/s2'
  get 'shoutouts/s3'
  get 'shoutouts/s4'
  get 'shoutouts/s5'
  get 'shoutouts/s6'
  get 'shoutouts/s7'
  get 'shoutouts/s8'
  get 'shoutouts/s9'
  get 'shoutouts/s10'
  get 'blog/b1'
  get 'blog/b2'
  get 'blog/b3'
  get 'blog/b4'
  get 'blog/b5'
  get 'blog/b6'
  get 'blog/b7'
  get 'blog/b8'
  get 'blog/b9'
  get 'blog/b10'
  get 'introduction/ch1'
  get 'introduction/ch2'
  get 'introduction/ch3'
  get 'introduction/ch4'
  get 'introduction/ch5'
  get 'introduction/ch6'
  get 'introduction/ch7'
  get 'introduction/ch8'
  get 'introduction/ch9'
  get 'introduction/ch10'
  get 'introduction/ch11'
  get 'introduction/ch12'
  get 'introduction/ch13'
  get 'introduction/ch14'
  get 'introduction/ch15'
  resources :intros
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'intro1', to: 'pages#intro1'

  resources :articles, only: [:show, :index, :new, :create]
  resources :icecreams, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :blogs, only: [:show]
  get 'signup', to: 'users#new'
end
